###

GET https://api.lessonly.com/api/v1/groups
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1/groups/{{ group-id }}/assignments
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1/users/{{ user-id }}/assignments
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1.1/assignments?page=1
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1.1/lessons?page=1
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1.1/paths
Authorization: Basic {{ subdomain }} {{ api-key }}

###

GET https://api.lessonly.com/api/v1.1/users?page=1
Authorization: Basic {{ subdomain }} {{ api-key }}
